export const WorkExperience = [
  {
    place: "PT ALTO Network",
    position: "Front-End Developer",
    start: "Jan 2024",
    end: "",
    projects: ["altoconnect.id"],
    stacks: ["NextJS, JavaScript, HTML, CSS, Bootstrap, Axios"],
    jobDesk: [
      "Assigned to work on Alto Connect project",
      "The project mainly focused on creating a one-gate-portal to majorities of Alto's Projects Dashboard. So that the users don't have to hit different URL on each dashboards.",
      "The main task here is to develop new features according to user requests and resolve existing bugs.",
      "For the main tech stack of this application, NextJS and JavaScript are used.",
      "Custom-built components & functions are created in order to use them globally.",
      "For API matters, Axios is used mainly.",
      "Participating in their Release & Deployment schedule sometimes.",
    ],
  },
  {
    place: "PT Tiga Daya Digital Indonesia (Eksad)",
    position: "Front-End Developer",
    start: "June 2022",
    end: "Dec 2023",
    projects: ["speed.autopedia.id"],
    stacks: ["NextJS, TypeScript, HTML, CSS, Bootstrap, Axios, React-Query"],
    jobDesk: [
      "Assigned to Autopedia Indonesia",
      "The internal administration called SPEED was assigned to me, which was integrated with a car sales application called Caroline.id",
      "It is ensured by me that this application runs smoothly with as few bugs as possible.",
      "The main task here is to develop new features according to requests and resolve existing bugs.",
      "For the main tech stack of this application, NextJS and TypeScript are used.",
      "Bootstrap is also used as the CSS Framework.",
      "For API matters, Axios and React-Query are used.",
    ],
  },
  {
    place: "PT ASQI Digital Innovation",
    position: "Freelance Front-End Developer",
    start: "Oct 2023",
    end: "",
    projects: ["ergb.co.id", "admin.ergb.co.id"],
    stacks: ["NextJS, TypeScript, HTML, CSS, MaterialUI, Axios, React-Query"],
    jobDesk: [
      "The project called RGB was assigned to me. It is a web application that functions for event ticket management.",
      "Both client-side and administrator-side are developed by me in the Front-End section.",
      "For the main tech stack of this application, NextJS and TypeScript are used.",
      "MUI is also used as the component library.",
      "For the main tech stack of this application, NextJS and TypeScript are used.",
      "For API matters, Axios and React-Query are used.",
      "This application is continuosly used for its main purpose for these past few months.",
      "You can access the app from the link attached below.",
    ],
  },
  {
    place: "HEXA DAYA SOLUSI",
    position: "Front-End Developer",
    start: "Dec 2021",
    end: "June 2022",
    projects: [],
    stacks: ["ReactJS, JavaScript, HTML, CSS, MaterialUI, Axios, Redux"],
    jobDesk: [
      "The project for the Government of Jakarta was assigned to me. It is an app that has main goal to monitor every government’s building in Jakarta’s water usage called ECO WATER.",
      "I use React.JS, Redux, Axios, & Material UI Framework for this project.",
      "The app is built by me to be user-friendly so that it’s easy to use and mobile-friendly using CSS Responsive Breakpoints.",
    ],
  },
  {
    place: "PT CROWDE Membangun Bangsa",
    position: "Junior Front-End Developer",
    start: "July 2021",
    end: "Dec 2021",
    projects: [],
    stacks: ["ReactJS, JavaScript, HTML, CSS, Bootstrap, Axios, Redux"],
    jobDesk: [
      "The company-internal React.JS based projects called AGSales & Ops Panel were dealt with by me.",
      "Some of their Web Design from UI Design in Figma was sliced by me to React.JS Front-End.",
      "The API was integrated to the Front-End by me.",
      "A variety of Front-End based bugs were dealt with by me and fixed so that the project ran properly.",
    ],
  },
  {
    place: "PT LENMARC Exa Abadi Digital",
    position: "Junior Front-End Developer",
    start: "July 2021",
    end: "Dec 2021",
    projects: ["lemtron.id"],
    stacks: ["JavaScript, HTML, CSS, Bootstrap, Laravel, PHP"],
    jobDesk: [
      "I built an online training app called LEMTRON (lemtron.id).",
      "Laravel & Bootstrap were used by me for this project since I only handle the Front-End side.",
      "The LEMTRON and other projects was tested by me so it can run properly as a Quality Assurance.",
    ],
  },
];

export const SkillAbilities = [
  "Problem Solving",
  "NextJS",
"ReactJS",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Material UI",
  "Bootstrap",
  "Axios",
  "React-Query",
  "Redux",
  "Analytical Thinking",
  "UI Slicing",
  "Clean Code Implementation",
  "Atomic Folder Structure",
];
